import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/Sidebar";
import Message from "@/components/Message";
import { getCookie } from "@/utils/cookie";
import { useRouter } from "next/router";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const isAuthenticated = getCookie("userInfo");

  useEffect(() => {
    // Check if the user is authenticated, otherwise redirect

    // Authentication check logic
    if (!isAuthenticated) {
      router.push("/sign-in"); // Redirect to login page
    } else {
      router.push("/messages");
    }
  }, []);
  return (
    <>
      <Head>
        <title>Sleek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
